/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as GraphRouteImport } from './routes/graph'
import { Route as GuardianRouteImport } from './routes/guardian'
import { Route as GuardiansRouteImport } from './routes/guardians'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PlaybookRouteImport } from './routes/playbook'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as GuardianIndexRouteImport } from './routes/guardian/index'
import { Route as GuardianPortalRouteImport } from './routes/guardian/portal'
import { Route as GuardianInviteTokenRouteImport } from './routes/guardian/invite/$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphRoute = GraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const GuardianRoute = GuardianRouteImport.update({
  id: '/guardian',
  path: '/guardian',
  getParentRoute: () => rootRouteImport,
} as any)
const GuardiansRoute = GuardiansRouteImport.update({
  id: '/guardians',
  path: '/guardians',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaybookRoute = PlaybookRouteImport.update({
  id: '/playbook',
  path: '/playbook',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const GuardianIndexRoute = GuardianIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GuardianRoute,
} as any)
const GuardianPortalRoute = GuardianPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => GuardianRoute,
} as any)
const GuardianInviteTokenRoute = GuardianInviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => GuardianRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/graph': typeof GraphRoute
  '/guardian': typeof GuardianRouteWithChildren
  '/guardians': typeof GuardiansRoute
  '/login': typeof LoginRoute
  '/playbook': typeof PlaybookRoute
  '/signup': typeof SignupRoute
  '/upload': typeof UploadRoute
  '/guardian/portal': typeof GuardianPortalRoute
  '/guardian/': typeof GuardianIndexRoute
  '/guardian/invite/$token': typeof GuardianInviteTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/graph': typeof GraphRoute
  '/guardians': typeof GuardiansRoute
  '/login': typeof LoginRoute
  '/playbook': typeof PlaybookRoute
  '/signup': typeof SignupRoute
  '/upload': typeof UploadRoute
  '/guardian/portal': typeof GuardianPortalRoute
  '/guardian': typeof GuardianIndexRoute
  '/guardian/invite/$token': typeof GuardianInviteTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/graph': typeof GraphRoute
  '/guardian': typeof GuardianRouteWithChildren
  '/guardians': typeof GuardiansRoute
  '/login': typeof LoginRoute
  '/playbook': typeof PlaybookRoute
  '/signup': typeof SignupRoute
  '/upload': typeof UploadRoute
  '/guardian/portal': typeof GuardianPortalRoute
  '/guardian/': typeof GuardianIndexRoute
  '/guardian/invite/$token': typeof GuardianInviteTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/dashboard'
    | '/graph'
    | '/guardian'
    | '/guardians'
    | '/login'
    | '/playbook'
    | '/signup'
    | '/upload'
    | '/guardian/portal'
    | '/guardian/'
    | '/guardian/invite/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/dashboard'
    | '/graph'
    | '/guardians'
    | '/login'
    | '/playbook'
    | '/signup'
    | '/upload'
    | '/guardian/portal'
    | '/guardian'
    | '/guardian/invite/$token'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/dashboard'
    | '/graph'
    | '/guardian'
    | '/guardians'
    | '/login'
    | '/playbook'
    | '/signup'
    | '/upload'
    | '/guardian/portal'
    | '/guardian/'
    | '/guardian/invite/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  GraphRoute: typeof GraphRoute
  GuardianRoute: typeof GuardianRouteWithChildren
  GuardiansRoute: typeof GuardiansRoute
  LoginRoute: typeof LoginRoute
  PlaybookRoute: typeof PlaybookRoute
  SignupRoute: typeof SignupRoute
  UploadRoute: typeof UploadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph': {
      id: '/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof GraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guardian': {
      id: '/guardian'
      path: '/guardian'
      fullPath: '/guardian'
      preLoaderRoute: typeof GuardianRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guardians': {
      id: '/guardians'
      path: '/guardians'
      fullPath: '/guardians'
      preLoaderRoute: typeof GuardiansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playbook': {
      id: '/playbook'
      path: '/playbook'
      fullPath: '/playbook'
      preLoaderRoute: typeof PlaybookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guardian/': {
      id: '/guardian/'
      path: '/'
      fullPath: '/guardian/'
      preLoaderRoute: typeof GuardianIndexRouteImport
      parentRoute: typeof GuardianRoute
    }
    '/guardian/portal': {
      id: '/guardian/portal'
      path: '/portal'
      fullPath: '/guardian/portal'
      preLoaderRoute: typeof GuardianPortalRouteImport
      parentRoute: typeof GuardianRoute
    }
    '/guardian/invite/$token': {
      id: '/guardian/invite/$token'
      path: '/invite/$token'
      fullPath: '/guardian/invite/$token'
      preLoaderRoute: typeof GuardianInviteTokenRouteImport
      parentRoute: typeof GuardianRoute
    }
  }
}

interface GuardianRouteChildren {
  GuardianPortalRoute: typeof GuardianPortalRoute
  GuardianIndexRoute: typeof GuardianIndexRoute
  GuardianInviteTokenRoute: typeof GuardianInviteTokenRoute
}

const GuardianRouteChildren: GuardianRouteChildren = {
  GuardianPortalRoute: GuardianPortalRoute,
  GuardianIndexRoute: GuardianIndexRoute,
  GuardianInviteTokenRoute: GuardianInviteTokenRoute,
}

const GuardianRouteWithChildren = GuardianRoute._addFileChildren(
  GuardianRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  GraphRoute: GraphRoute,
  GuardianRoute: GuardianRouteWithChildren,
  GuardiansRoute: GuardiansRoute,
  LoginRoute: LoginRoute,
  PlaybookRoute: PlaybookRoute,
  SignupRoute: SignupRoute,
  UploadRoute: UploadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
